#before_script:
#  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
#  - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
#  - eval $(ssh-agent -s)
#  - ssh-add <(echo "$DEPLOY_KEY")
#  - mkdir -p ~/.ssh
#  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
#
#stages:
#  - build
#  - deploy
#
#minify:
#  stage: build
#  script:
#  # здесь задается список скриптов для сборки верстки
#  # таких скриптов может быть несколько(верстка сайта, верстка личного кабинета, верстка второго сайта)
#  # укажите путь папке, в которой находится верстка
#  - cd $CI_PROJECT_DIR/working/layout && npm install && npm run minify
#  artifacts:
#    paths:
#    # укажите список путей с результатами сборки
#    - working/layout/dist/
#    expire_in: 1 week
#
#job_deploy_to_staging:
#  stage: deploy
#  environment:
#    name: staging
#    url: http://wireframes.cetera.ru/$CI_PROJECT_NAME/layout/
#  script:
#  # здесь задается список скриптов для выкладки результатов сборки на сервер
#  # таких скриптов может быть несколько
#  # укажите путь к папке, в которой находится верстка
#  - rsync -avuz  --numeric-ids --chown=33:33 -e ssh $CI_PROJECT_DIR/working/layout/dist/ vps10.cetera.ru::wireframe/$CI_PROJECT_NAME/layout/
#  only:
#  - master
#  when: always # always | manual
