<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();
$aMenuLinks = Array(
    Array(
        "Новинки",
        "about/howto/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Бренды",
        "about/delivery/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Одежда",
        "about/contacts/",
        Array(),
        Array("section_id"=>StockMan\Config::INDEX_CATALOG_SECTION_ID_1),
        ""
    ),
    Array(
        "Обувь",
        "personal/",
        Array(),
        Array("section_id"=>StockMan\Config::INDEX_CATALOG_SECTION_ID_2),
        ""
    ),
    Array(
        "Сумки",
        "catalog/",
        Array(),
        Array()
    ),
    Array(
        "Аксессуары",
        "catalog/",
        Array(),
        Array()
    ),
    Array(
        "Белье",
        "catalog/",
        Array(),
        Array()
    ),
    Array(
        "SALE",
        "catalog/",
        Array(),
        Array()
    ),
    Array(
        "Блог",
        "catalog/",
        Array(),
        Array()
    )
);
?>